/**
 * Dark theme — semantic tokens (curated dark UI aligned with light theme keys).
 */
export const darkVariables = {
  '16': '16',
  'text/default': '#f2efff',
  'text/label/sm/font-size': '14',
  'Font/Font-Family': 'Bitvavo Sans Variable',
  'text/label/sm/line-height': '14',
  'text/Font-weight-medium': '600',
  'text/brand': '#b794f6',
  'component/button/link/text': '#b794f6',
  'component/link/sm/gap': '4',
  'component/link/md/container-height': '20',
  'component/slider/slider-radius': '999',
  'component/Slider/bg-slider-inactive': '#1f1a2e',
  'custom/slider/inactive-container-border': '#2d2840',
  'component/slider/ruler-height': '8',
  'component/Slider/ruler/ruler-inactive': '#6b6588',
  'component/slider/ruler-padding-y': '0',
  'component/slider/ruler-padding-x': '12',
  'component/Slider/dots': '#4a4460',
  'component/step/gap': '4',
  'component/slider/height-inactive': '16',
  'component/Slider/bg-container': '#14121c',
  'component/Slider/bg-slider-track-rail': '#262033',
  'component/Slider/border-container': '#2a2536',
  'component/slider/wrapper-gap': '4',
  'component/button/primary/text': '#ffffff',
  'text/body/xs/font-size': '13',
  'text/body/xs/line-height': '20',
  'Weight/medium': '500',
  'component/button/sm/gap': '4',
  'component/button/xs/padding-x': '16',
  'component/button/xs/padding-y': '4',
  'component/button/xs/container-height': '28',
  'component/button/xs/radius-round': '100',
  'component/button/primary/bg-start': '#9e4ed9',
  'component/Slider/bg-slider-active': '#9e4ed9',
  'component/Slider/border-active': '#c084fc',
  'component/Slider/ruler/ruler-active': '#e8ddff',
  'component/slider/height-active': '16',
  'border/default': '#2a2536',
  'surface/bg-low': '#0e0c12',
  'effect/shadow': '#000000',
  'component/Slider/tick-on-fill': '#e8ddff',
} as const;

export type DarkVariableKey = keyof typeof darkVariables;
